#!/bin/bash

# print the very cool header
header() {
    echo '      __    __          __   /   __  _/_  _/_    __    __'
    echo '    /   ) /___)| /| /  (_ ` /  /___) /    /    /___) /   `'
    echo '___/___/_(___ _|/_|/__(__)_/__(___ _(_ __(_ __(___ _/____v2.0___'
    echo
}

helper () {
    header
    cat <<'EOF'
This will send a newsletter to every mail addresses listed in the emails
file in config folder.

Usage: newsletter [-c CONFIG_PATH] [-n EMAIL_NAME] SUBJECT [CONTENT_FILE]

  -c CONFIG_PATH    override the default config path
  -n EMAIL_NAME     override the email name
  -h                print this help
  -i                initialize .forward files

SUBJECT: the main subject of your newsletter.
(Use quotes for multi words name ex: 'La grande fête du morbier')

CONTENT_FILE: path to the file that store the content of your newsletter.
Alternatively, you can pipe the content through STDIN.

The default From address will use your club1 username like this:
USER@club1.fr, but can be overidden using -c argument.

Git repo: <https://github.com/club-1/newsletter>
EOF
}

# initialize newsletter
# {{PREFIX}} will be replaced during install with Make.
init() {
    echo '| {{PREFIX}}/sbin/nl subscribe' > "$HOME/.forward+subscribe"
    echo '| {{PREFIX}}/sbin/nl confirm' > "$HOME/.forward+confirm"
    echo '| {{PREFIX}}/sbin/nl unsubscribe' > "$HOME/.forward+unsubscribe"
    echo 'created 3 .forward files (+subscribe, +confirm, +unsubscribe)'
}


# default newsletter email name is username
nl="$USER"
# default config path location
configPath="$HOME/.config/newsletter"

while getopts 'n:c:hi' opt
do
    case $opt in
        c)
            # overide config path
            configPath="$OPTARG"
        ;;
        n)
            # overide newsletter email name
            nl="$OPTARG"
        ;;
        h)
            helper
            exit 0
        ;;
        i)
            init
            exit 0
        ;;
        *)
            helper
            exit 2
        ;;
    esac
done
shift "$(($OPTIND -1))"

# if the config folder does not exist, abort here
if test ! -d "$configPath"
then
    echo "config path '$configPath' is not a valid folder."
    exit 2
fi

# if the newsletter name is not valid, abort here
if ! $(expr "$nl" : '^[a-z0-9-]\{3,17\}$' > /dev/null)
then
    echo "newsletter email '$nl@club1.fr' is not valid"
    exit 2
fi

# check presence of first arg
if test -z "$1"
then
    echo 'First argument should be the newsletter title'
    exit 2
fi


# check presence of second arg or STD IN
if test -n "$2"
then
    if test -f "$2"
    then
        content=$(cat "$2")
    else
        echo "file $2 does not exist"
        exit 2
    fi
else
    if test ! -t 0
    then
        content=$(cat)
    else
        echo 'No content found. Provide a filename as second argument or pipe a text through STDIN'
        exit 2
    fi
fi


settingsFile="$configPath/settings.json"
emailsFile="$configPath/emails"
signatureFile="$configPath/signature.txt"

mkdir -p "$configPath"

header

echo '📜 reading configuration'

if test ! -f "$settingsFile"
then
    echo '⚠️ no file "~/config/newsletter/settings.json" found, a default one was created.'
    jq -n '.title = "" | .displayName = ""' >> "$settingsFile"
fi

if test ! -f "$signatureFile"
then
    echo '⚠️ no file "~/config/newsletter/signature.txt" found, an empty one was created.'
    touch "$signatureFile"
fi

if test ! -f "$emailsFile"
then
    echo '⚠️ no file "~/config/newsletter/mails" found, a default one was created.'
    echo 'This file should contain the emails you want to send the newsletter to.'
    echo 'An empty one was created'
    touch "$emailsFile"
    exit 1
fi

displayName=$(cat "$settingsFile" | jq -r '.displayName // ""')
title=$(cat "$settingsFile" | jq -r '.title // ""')
signature=$(cat "$signatureFile")

unsubscribe="Pour vous désinscrire, vous pouvez envoyer un email a : <$nl+unsubscribe@club1.fr>"

if test -n "$signature"
then
    content="$content\n-- \n$signature\n\n$unsubscribe"
else
    content="$content\n-- \n$unsubscribe"
fi

if test -n "$displayName"
then
    from="$displayName <$nl@club1.fr>"
else
    from="$nl@club1.fr"
fi

if test -n "$title"
then
    subject="[$title] $1"
else
    subject="$1"
fi

# read emails file while removing blank lines
emails=$(grep -v -e '^$' "$emailsFile")

# remove duplicates using -u (unique)
uniqueEmails=$(echo -n "$emails" | sort -u)

# count the number of emails
count=$(echo -n "$uniqueEmails" | wc -l)

# estimate sending time, here for 0.2 sec per email
time=$(($count / 5))

echo
echo -e "███████████████████████████████████\e[7m HEADER \e[27m████████████████████████████████████"

echo "Subject: $subject"
echo "From: $from"

echo -e "███████████████████████████████████\e[7m CONTENT \e[27m███████████████████████████████████"
echo -e "$content" | fold -w 80 -s
echo -e "███████████████████████████████████████████████████████████████████████████████"

echo

echo "Do you really want to send this to $count unique email addresses ? y/[n]"
echo "(estimated sending time is $time seconds)"

# read user input for consent
# inspired by first method from answer <https://stackoverflow.com/a/54396662>
read -rsn1 consent <&2

if test "$consent" != 'y'
then
    echo "sending aborted"
    exit 3
fi

printf '📨 sending'

echo -n "$uniqueEmails" | while read addr
do
    echo -e "$content" | qprint --encode | mailx \
        -s "$subject" \
        -a "List-Unsubscribe: <mailto:$nl+unsubscribe@club1.fr>" \
        -a "Content-Transfer-Encoding: quoted-printable" \
        -r "$from" \
        -- "$addr"
    printf '.'
    sleep 0.2
done
echo 'done !'
exit 0

