#!/bin/bash -e

# basic email template that setup headers and add footer
# sendEmail SUBJECT BODY [CUSTOM_MAILX_ARGS...]
sendEmail() {
    local subject="$1"
    local body="$2"
    shift 2

    local content="$body$footer"
    echo -e "$content" | qprint --encode | mailx \
        -s "$subject" \
        -a "List-Unsubscribe: <mailto:$nl+unsubscribe@club1.fr>" \
        -a 'Content-Transfer-Encoding: quoted-printable' \
        -a 'Content-Type: text/plain; charset=UTF-8' \
        -a "In-Reply-To: $emailMessageId" \
        "$@" \
        -r "$displayName <$nl@club1.fr>" \
        -- "$emailFrom"
}


# If the email address is aleary listed, we stop here and send an email
checkAlreadySubscribed () {
    if test $exist != 0
    then
        sendEmail \
            "Votre email est déjà inscrit à $extendedTitle" \
            "Pour vous désinscrire, vous pouvez envoyer un email à : $nl+unsubscribe@club1.fr"
        exit
    fi
}

# return content of .secret file
# if the file does'nt exist yet, it's created
getSecret() {
    if test ! -s "$configPath/.secret"
    then
        head -c 30 /dev/urandom | base64 > "$configPath/.secret"
        touch "$configPath/.secret"
        chmod 600 "$configPath/.secret"
    fi
    echo $(cat "$configPath/.secret")
}

# generate a hash based on given string and .secret
hashWithSecret () {
    secret="$(getSecret)"
    hash=$(echo -n "$1$secret" | sha256sum | cut -b 1-16)
    echo "$hash"
}

# generate an identifier like `<NLNAME-XXXXX@club1.fr>` thanks to a given string
generateID () {
    echo "<$nl-$1@club1.fr>"
}

# get confirmation ID based on From header
confirmID () {
    hash="$(hashWithSecret "$emailFrom")"
    id="$(generateID "$hash")"
    echo "$id"
}

subscribe () {
    checkAlreadySubscribed

    sendEmail \
        "Inscription à $extendedTitle" \
        "Veuillez repondre a cet email pour confirmer que vous souhaitez recevoir $extendedTitle.\
        \nVous recevrez un email de confirmation. (n'oubliez pas vérifier vos courriers indésirables !)" \
        -a "Message-Id: $(confirmID)" -a "Reply-to: $nl+confirm@club1.fr"
}

unsubscribe () {
    # If it exist, we delete it. Otherwise we send an email indicating the mistake
    if test $exist = 1
    then
        tmpemails=$(sed "/^$emailFrom\$/d" "$emails")
        echo "$tmpemails" > "$emails"
        sendEmail \
            "Vous avez bien été retiré de $extendedTitle" \
            "Votre email <$emailFrom> a bien été retiré des abonnements à $extendedTitle.\
            \n\nPour vous réinscrire, il vous suffit d'envoyer un email à <$nl+subscribe@club1.fr> à tout moment."
    else
        sendEmail \
            "Votre email n'est pas inscrit à $extendedTitle" \
            "On ne peut donc pas le retirer. Si le problème persiste, veuillez contacter <postmaster@club1.fr>"
    fi
}

confirm () {
    checkAlreadySubscribed

    # get the In-Reply-To header
    emailInReplyTo=$(echo "$mail" | grep -Eoi -m 1 "^In-Reply-To: .*" | grep -Eo "<.*>")

    # comparaison  against the localy generated ID
    if test $emailInReplyTo = $(confirmID)
    then
        echo "$emailFrom" >> "$emails"
        sendEmail \
            "Confirmation d'inscription à $extendedTitle" \
            "C'est bon!\nVotre email <$emailFrom> a bien été ajouté. \
            \nPour vous désinscrire, vous pouvez envoyer un email a : <$nl+unsubscribe@club1.fr>"
    else
        sendEmail \
            "Erreur lors de la confirmation d'inscription à $extendedTitle" \
            "L'adresse de provenance : <$emailFrom> ne correspond pas."
    fi
}

send () {
    # check if email from match user
    if test "$emailFrom" = "$nl@club1.fr"
    then
        # get email body
        emailBody=$(echo "$mail" | sed -e '1,/^$/ d' )

        # get email subject
        emailSubject=$(echo "$mail" | sed '/^Subject: */!d; s///;q')

        hash="$(hashWithSecret "$emailBody$emailSubject")"
        sendID="$(generateID "$hash")"

        # store body and subject as temporary files
        echo "$emailBody" > "/tmp/newsletter-send-$hash.body.txt"
        echo "$emailSubject" > "/tmp/newsletter-send-$hash.subject.txt"

        # run newsletter script
        # {{PREFIX}} will be replaced during install with Make.
        response="$(echo "$emailBody" | {{PREFIX}}/bin/newsletter -mn "$emailSubject" )"

        sendEmail \
            "Confirmation d'envoi" \
            "$response" \
            -a "Message-Id: $sendID" -a "Reply-to: $nl+send-confirm@club1.fr"
    fi
}

sendConfirm () {
    # get the In-Reply-To header
    emailInReplyTo=$(echo "$mail" | grep -Eoi -m 1 "^In-Reply-To: .*" | grep -Eo "<.*>")

    # retrieve hash from mail address ID
    prefix="<$nl-"
    suffix="@club1.fr>"
    hash=${emailInReplyTo#"$prefix"}
    hash=${foo%"$suffix"}

    # abort if no matching files are found
    if test ! -f "/tmp/newsletter-send-$hash.body.txt" || test ! -f "/tmp/newsletter-send-$hash.subject.txt"
    then
        exit 1
    fi

    subject=$(cat "/tmp/newsletter-send-$hash.subject.txt")

    # lauch newsletter script
    result=$({{PREFIX}}/bin/newsletter -ym "$subject" "/tmp/newsletter-send-$hash.body.txt")

    # delete temporary files
    rm "/tmp/newsletter-send-$hash.body.txt"
    rm "/tmp/newsletter-send-$hash.subject.txt"

    sendEmail \
        "La newsletter est partie 🏁" \
        "$result"
}



# Default config path location
configPath="$HOME/.config/newsletter"
# store stdin (standard input)
mail=$(cat)
# default email username is current user's name
nl="$USER"

while getopts 'c:' opt
do
    case $opt in
        c)
            # overide config path
            configPath="$OPTARG"

            # if the config folder does not exist, abort here
            if test ! -d "$configPath"
            then
                echo "config path '$configPath' is not a valid folder."
                exit 2
            fi
        ;;
        *)
            echo 'invalid flag(s)'
            exit 2
        ;;
    esac
done
shift "$(($OPTIND -1))"

mkdir -pv "$configPath"

# associate first arg with sub-command
subcmd=$1


# check if email have Autosubmitted Header
# if so, abort mission and prevent daemon to send any error email to avoid infinite bouncing
autoSubmitted=$(echo "$mail" | grep -cEi -m 1 "^Auto-Submitted:" || test $? = 1)

if test "$autoSubmitted" = 1
then
    exit 1
fi

# look for first line containing `From: ` and store it in var
from=$(echo "$mail" | grep -Ei -m 1 "^From: ")
emailFrom=$(echo "$from" | grep -E -m 1 -o "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}\b")

# get the message ID thanks to the associated mail header
emailMessageId=$(echo "$mail" | grep -Eoi -m 1 "^Message-Id: .*" | grep -Eo "<.*>")

# path to file containing subscribed emails
emails="$configPath/emails"

# check if the from address is listed in the subscribed emails file.
# `0` is stored if not listed. `1` is stored if listed.
exist=$(grep -c -x -m 1 "$emailFrom" "$emails" || test $? = 1)

# read the title of the newsletter and the from display name
settingsFile="$configPath/settings.json"
title=$(cat "$settingsFile" | jq -r '.title // ""')
displayName=$(cat "$settingsFile" | jq -r '.displayName // ""')

# define extended title: how the newsletter is called in the email
if test -n "$title"
then
    extendedTitle="la newsletter [$title]"
else
    extendedTitle="la newsletter de $USER"
fi

# load a signature from the corresponding file
signatureFile="$configPath/signature.txt"
if test -f "$signatureFile"
then
    signature=$(cat "$signatureFile")
    footer="\n-- \n$signature"
else
    footer=''
fi

# lauch matching sub-command
case $subcmd in
    'subscribe') subscribe;;
    'unsubscribe') unsubscribe;;
    'confirm') confirm;;
    'send') send;;
    'send-confirm') sendConfirm;;
    *) echo 'this sub-command does not exist'
    exit 2;;
esac
